- hosts: nodes
  become: yes
  become_method: sudo
  vars_files:
    - "global_vars.yml"
  roles:
    - common
    - security

- hosts: portworx
  become: yes
  become_method: sudo
  vars_files:
    - "global_vars.yml"
  roles:
    - volume

- hosts: portworx_tester_node
  become: yes
  become_method: sudo
  roles:
    - volume-check
