- name: checking cluster status
  command: /opt/pwx/bin/pxctl -j status
  register: clusterstatus
  failed_when: '(clusterstatus.stdout | from_json).status != "STATUS_OK"'

- name: check volume exists
  shell: /opt/pwx/bin/pxctl volume list | grep -w myvol
  register: volexists
  ignore_errors: yes

- name: volume create
  command: /opt/pwx/bin/pxctl volume -j create -r 1 myvol
  register: myvolcreate
  when: volexists.rc != 0

- set_fact:
    testvolumeid: "{{ (myvolcreate.stdout | from_json).uuid[0] }}"

- name: save variable across plays
  add_host:
    name: "portworx_vars"
    testvolumeid: "{{ testvolumeid }}"

- name: volume inspect
  command: /opt/pwx/bin/pxctl -j volume inspect {{ testvolumeid }}
  register: vi
  until: '(vi.stdout | from_json)[0].runtime_state[0].runtime_state.RuntimeState == "clean"'
  retries: 5
  delay: 2

